
name : Deploy


on   : [push]


jobs : 
  build :
    runs-on : ubuntu-latest

    
    steps :
    - uses: actions/checkout@v1


    - name: Copy repository contents on scp
      uses: appleboy/scp-action@master
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.SSHKEY }}
      source: "."
      target: "/var/www/test2" 
   


